# Generated by Django 2.0.5 on 2018-06-02 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('datePub', models.DateTimeField(default=datetime.datetime(2018, 6, 2, 17, 32, 27, 919432), null=True)),
                ('dateDelai', models.DateTimeField(null=True)),
                ('statusAnnonce', models.BooleanField(default=True)),
                ('valid', models.BooleanField(default=False)),
                ('nbVue', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assoDevis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TVA', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('quantite', models.IntegerField(null=True)),
                ('prixUTH', models.FloatField(null=True)),
                ('devisFile', models.FileField(null=True, upload_to='appelsOffres/devis')),
            ],
        ),
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ifFile', models.BooleanField(default=False)),
                ('ifForm', models.BooleanField(default=False)),
                ('devisAss', models.ManyToManyField(to='appelsOffres.assoDevis')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annonce', models.ForeignKey(on_delete=False, to='appelsOffres.Annonce')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fonction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fonction', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ImageScrol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageScrol', models.ImageField(upload_to='appelsOffres')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, null=True)),
                ('categorie', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('estimation', models.FloatField()),
                ('cautionProvisoire', models.FloatField()),
                ('qualifications', models.CharField(max_length=255, null=True)),
                ('Agrements', models.CharField(max_length=255, null=True)),
                ('echantillons', models.TextField()),
                ('visiteLieux', models.TextField()),
                ('variante', models.CharField(max_length=100)),
                ('reservePME', models.CharField(max_length=100)),
                ('cahierDeCharge', models.FileField(upload_to='appelsOffres/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='devis',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appelsOffres.Lot'),
        ),
        migrations.AddField(
            model_name='devis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='devis',
            field=models.ManyToManyField(to='appelsOffres.Devis'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='lot',
            field=models.ManyToManyField(to='appelsOffres.Lot'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
