# Generated by Django 2.0.5 on 2018-06-02 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appelsOffres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='datePub',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 18, 45, 53, 906492), null=True),
        ),
    ]
