# Generated by Django 2.0.5 on 2018-06-02 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appelsOffres', '0003_auto_20180602_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='datePub',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 18, 51, 33, 100893), null=True),
        ),
    ]
