from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(DemandeAmi)
admin.site.register(DemandeGroupe)
admin.site.register(Conversation)
admin.site.register(Responseconversation)
admin.site.register(Groupe)
admin.site.register(Commentaire)
admin.site.register(Statut)
admin.site.register(Suivie)
admin.site.register(Notification)
admin.site.register(ReseauSocialFile)
admin.site.register(ActionBenevole)
admin.site.register(Ecole)
admin.site.register(Experience)
admin.site.register(Formation)
admin.site.register(Langue)
admin.site.register(OffreEmploi)
admin.site.register(Organisme)
admin.site.register(Poste)
admin.site.register(NiveauLangue)
admin.site.register(LangueProfil)
admin.site.register(PageEntreprise)
admin.site.register(Reply)
admin.site.register(StatutSignales)
admin.site.register(CommentaireSignales)
admin.site.register(ReplySignales)
