from django.urls import path
from ecommerce import views

app_name = 'e_commerce'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id_request>/', views.test, name='test'),
    path('search/', views.search, name='search'),
    path('products/', views.products, name='products'),
    # ADD PRODUCT
    path('products/add/', views.add_product, name='add_product'),
    path('products/add/upload_image/', views.product_upload_image, name='product_upload_image'),
    path('products/add/delete_image/<int:image_id>/', views.product_delete_image, name='product_delete_image'),
    path('products/add/stock/', views.product_add_stock, name='product_add_stock'),
    path('products/add/specification/', views.product_add_specification, name='product_add_specification'),
    path('products/add/detail/', views.product_add_detail, name='product_add_detail'),
    path('products/add/tag/', views.product_add_tag, name='product_add_tag'),
    path('products/add/cancel/', views.product_cancel, name='product_cancel'),
    path('product/update/<int:product_id>/', views.update_product, name='product_update'),
    path('products/update/upload_image/<int:product_id>/', views.up_product_upload_image, name='up_product_upload_image'),
    path('products/update/delete_image/<int:product_id>/<int:image_id>/', views.up_product_delete_image, name='up_product_delete_image'),
    path('products/update/delete_spec/<int:product_id>/<int:spec_id>/', views.up_product_delete_spec, name='up_product_delete_spec'),
    path('products/update/delete_detail/<int:product_id>/<int:detail_id>/', views.up_product_delete_detail, name='up_product_delete_detail'),
    path('products/update/delete_stock/<int:product_id>/<int:stock_id>/', views.up_product_delete_stock, name='up_product_delete_stock'),
    path('products/update/stock/<int:product_id>/', views.up_product_add_stock, name='up_product_add_stock'),
    path('products/update/specification/<int:product_id>/', views.up_product_add_specification, name='up_product_add_specification'),
    path('products/update/detail/<int:product_id>/', views.up_product_add_detail, name='up_product_add_detail'),
    path('products/update/tag/<int:product_id>/', views.up_product_add_tag, name='up_product_add_tag'),
    path('account/upgrade/', views.create_store, name='create_store'),
    path('products/<str:type_search>/<str:id_search>/', views.products, name='products'),
    path('products_sub/<str:type_search>/<str:id_search>/', views.products_sub, name='products_sub'),
    path('product/', views.display_product, name='product'),
    path('product/<str:id_product>/', views.display_product, name='product'),
    path('quick_view/<str:id_product>/', views.quick_view, name='quick_view'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/history/', views.order_history, name='order_history'),
    path('information/order/<str:id_order>/', views.order_information, name='order_information'),
    path('suppliers/', views.suppliers_list, name='suppliers'),
    path('supplier/<str:id_supplier>/', views.display_supplier, name='supplier'),
    path('account/products/', views.your_products, name='your_products'),
    path('product/remove/', views.remove_product, name='remove_product'),
    path('categories/', views.list_categories, name='list_categories'),
    path('review/', views.review, name='review'),
    path('orders/processing/', views.processing_orders, name="processing_orders"),
    path('orders/all/', views.all_orders, name="all_orders"),
    path('order/update/', views.update_order, name="update_order"),
    #--------------- Cart - wish list - compare - contact supplier
    path('cart/', views.cart, name='cart'),
    path('cart/update_cart/', views.update_cart, name='update_cart'),
    path('cart/update_color_cart', views.update_color_cart, name='update_color_cart'),
    path('cart/remove_from_page_cart', views.remove_from_page_cart, name='remove_from_page_cart'),
    path('wish_list/', views.wish_list, name='wish_list'),
    path('wish_list/add_from_wish/', views.add_from_wish, name='add_from_wish'),
    path('wish_list/remove_from_wish/', views.remove_from_wish, name='remove_from_wish'),
    path('compare/', views.compare, name='compare'),
    path('compare/add_from_compare/', views.add_from_compare, name='add_from_compare'),
    path('compare/remove_from_compare/', views.remove_from_compare, name='remove_from_compare'),
    path('add_to_compare', views.add_to_compare, name='add_to_compare'),
    path('add_to_wish_list', views.add_to_wish, name='add_to_wish_list'),
    path('add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart', views.remove_from_cart, name='remove_from_cart'),
    path('contact_supplier/<int:id_product>/', views.contact_supplier, name='contact_supplier'),
    # ------------ Easy
    path('contact-us/', views.contact_us, name='contact-us'),
    path('my-account/', views.my_account, name='my_account'),
    # ------------ Static pages
    path('FAQ/', views.faq, name='faq'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('about-us/', views.about_us, name='about-us'),
    #------------- Paypal
    path('paypal/process', views.paypal_process, name='paypal_process'),
    path('paypal/done', views.paypal_done, name='paypal_done'),
    path('paypal/cancel', views.paypal_cancel, name='paypal_cancel'),
]
